# SQL queries as variables to avoid any typo in code
SELECT = 'SELECT'
DELETE = 'DELETE'
UPDATE = 'UPDATE'
INSERT = 'INSERT'
VALUES = 'VALUES'
WHERE  = 'WHERE'
ORDER  = 'ORDER'
JOIN   = 'JOIN'
FROM   = 'FROM'
INTO   = 'INTO'
DESC   = 'DESC'
ASC    = 'ASC'
SET    = 'SET'